apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-server
  labels:
    app: product-server
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-server
      tier: backend
  template:
    metadata:
      name: product-server
      labels:
        app: product-server
        tier: backend
    spec:
      containers:
        - name: product-server
          image: ghcr.io/liberty52/liberty52-product-server:dev-v-2023.10.28-145414
          imagePullPolicy: IfNotPresent
#          resources:
#            requests:
#              memory: "2Gi"
#              cpu: "200m"
#            limits:
#              memory: "3Gi"
#              cpu: "400m"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
      imagePullSecrets:
        - name: ghcrcred
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: product-server
    tier: backend
  name: product-server
spec:
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: product-server
    tier: backend
