apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
  labels:
    tier: backend
    app: config-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      name: config-server
      labels:
        tier: backend
        app: config-server
    spec:
      containers:
        - name: config-server
          image: ghcr.io/liberty52/liberty52-config-server:dev-v0.1.2
          imagePullPolicy: Always
          resources:
            requests:
              memory: "200M"
              cpu: "400m"
            limits:
              memory: "250M"
              cpu: "400m"
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8888
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 15
            failureThreshold: 4
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8888
            periodSeconds: 15
            timeoutSeconds: 15
            failureThreshold: 7
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8888
            initialDelaySeconds: 120
            periodSeconds: 10
            timeoutSeconds: 15
            failureThreshold: 3
      imagePullSecrets:
        - name: ghcrcred