apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: auth-server
    tier: backend
  name: auth-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-server
      tier: backend
  strategy: {}
  template:
    metadata:
      labels:
        app: auth-server
        tier: backend
    spec:
      imagePullSecrets:
        - name: ghcrcred
      containers:
        - image: ghcr.io/liberty52/liberty52-auth-server:dev-v-2023.11.25-174526
          name: liberty52-auth-server

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: auth-server
    tier: backend
  name: auth-server
spec:
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: auth-server
    tier: backend
