apiVersion: v1
kind: Secret
metadata:
  name: jaeger-basic-auth
  namespace: istio-system
data:
  auth: YWRtaW46JGFwcjEkbWQvUVI1RzgkRFdrQmh1Zzlrb0FZTE1HaGt2ZHBELgo=
type: Opaque
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jaeger-ingress
  namespace: istio-system
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: jaeger-basic-auth
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required - ok'
spec:
  rules:
    - host: jaeger.liberty52.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tracing
                port:
                  number: 80