apiVersion: v1
kind: Service
metadata:
  labels:
    app: config-server
    tier: backend
  name: config-server
spec:
  selector:
    app: config-server
    tier: backend
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888