apiVersion: v1
kind: Service
metadata:
  labels:
    app: config-server
    tier: backend
  name: config-server
spec:
  ports:
  - port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    app: config-server