apiVersion: v1
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaGNyLmlvIjogewoJCQkiYXV0aCI6ICJhVzFyZFc1NWIzVnVaenBuYUhCZmMySlVOMWwyYTBOc05GWnZNek5YWWt3d1lXVllSR3cwTTJWYVVrNTVNVUp5UlhaWCIKCQl9Cgl9Cn0K
kind: Secret
metadata:
  name: ghcrcred
  namespace: local
type: kubernetes.io/dockerconfigjson