eksctl create nodegroup \
  --cluster bloomsburylab \
  --region ap-northeast-2 \
  --name t4g-largess \
  --node-type t4g.large \
  --nodes 1 \
  --nodes-min 1 \
  --nodes-max 1 \
  --node-volume-size 50 \
  --ssh-access \
  --max-pods-per-node=110